name: Docker Image CI
on:
  workflow_dispatch:
    
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USERNAME: ${{ github.actor }}
  REGISTRY: ghcr.io
  NAMESPACE: ${{ github.actor }}
  IMAGE_NAME: camino-time
  TAG: $(date +%s)

  
jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/${{ IMAGE_NAME }}:latest --tag ghcr.io/${{ github.actor }}/${{ IMAGE_NAME }}:${{ steps.version.outputs.version }}
        
      - name: ghcr login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login $REGISTRY -u $USERNAME --password-stdin
      - name: ghrc push latest
        run: docker push ghcr.io/${{ github.actor }}/${{ IMAGE_NAME }}:latest
      - name: ghrc push versioned
        run: docker push ghcr.io/${{ github.actor }}/${{ IMAGE_NAME }}:${{ steps.version.outputs.version }}
        
